"""
process csv files generated by db_process427.py.
Created: Friday, ‎November ‎19, ‎2021, ‏‎2:22:00 PM (EST)
@author: Xiaohuan (Pixel) X.
"""

import pandas as pd
import os

from db_process427 import save_df_to_csv
from utility427.helper427 import set_dir427, mkdir_p  # import helper functions from my own script


def main():
    """
    this script merge multiple csv files (both task and n-back);
    it
    1) increments id by the max from last csv + 1
    for task data only:
    2) change correct field: "correct" -> 1; "incorrect" -> 0
    for n-back only:
    2) remove rows who id is not present in task data
    14: _e427_live2a_5subs | ver = "26.427"
    15: _e427_live3_99subs | ver = "26.427"
    """
    which_dbs = [16]  # which database we want to combine
    type_dbs = ["serial_response", "n_back"]
    prefix_dbs = ["task_all_dbver", "n_back_all_dbver"]
    script_cwd = set_dir427()

    ids_unique = dict()  # unique id in task data (per which_dbs); unincremented

    for i, db in enumerate(type_dbs):
        cwd = script_cwd + f"/input/{db}/"
        df_dict = dict()
        temp = os.listdir(cwd)
        max_id = 0
        for name in temp:
            if name.startswith(prefix_dbs[i]):
                dbver = int(name.split("-")[0][len(prefix_dbs[i]):])
                if dbver in which_dbs:
                    df_dict[dbver] = pd.read_csv(cwd + name, index_col=0)
                    if db == "serial_response":
                        ids_unique[dbver] = df_dict[dbver]["id"].unique()
                        df_dict[dbver]["correct"] = df_dict[dbver]["correct"].apply(lambda x: int(x))
                    elif db == "n_back":
                        mask = df_dict[dbver]["id"].apply(lambda x: x in ids_unique[dbver])
                        df_dict[dbver] = df_dict[dbver][mask]
                    df_dict[dbver]["id"] += max_id
                    max_id = df_dict[dbver]["id"].max() + 1

        df = pd.concat([df_dict[x] for x in df_dict], ignore_index=True)
        save_df_to_csv(df, "", f"{prefix_dbs[i]}", show_df=False, index=False)


if __name__ == "__main__":
    main()
